---
- name: install tomcat9 and tomcat9-admin
  hosts: Test
  become: true
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: ["tomcat9", "tomcat9-admin"]
        state: present
        update_cache: yes
